### ISSUE TITLE
write_table with pretty and no data 

### ISSUE THREAD

**Issue by maasha** [maasha/BioDSL#16]
```
ERROR
undefined method `each' for nil:NilClass
/home/maasha/install/lib/ruby/gems/2.1.0/gems/terminal-table-1.4.5/lib/terminal-table/row.rb:19:in `initialize'
/home/maasha/install/lib/ruby/gems/2.1.0/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:100:in `new'
/home/maasha/install/lib/ruby/gems/2.1.0/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:100:in `headings='
/home/maasha/install/src/biopieces/lib/biopieces/commands/write_table.rb:255:in `block (2 levels) in write_table'
/home/maasha/install/src/biopieces/lib/biopieces/helpers/status_helper.rb:57:in `call'
/home/maasha/install/src/biopieces/lib/biopieces/helpers/status_helper.rb:57:in `status_track'
/home/maasha/install/src/biopieces/lib/biopieces/commands/write_table.rb:202:in `block in write_table'
/home/maasha/install/src/biopieces/lib/biopieces/pipeline.rb:286:in `call'
/home/maasha/install/src/biopieces/lib/biopieces/pipeline.rb:286:in `run'
```

**Comment by maasha** [comment]
Fixed: 6fa1b34
