### ISSUE TITLE
clip_primer with search distance > sequence length raises

### ISSUE THREAD

**Issue by maasha** [maasha/BioDSL#5]
```
biopieces-0.3.6/lib/biopieces/seq/backtrack.rb:115:in `patscan': stop: 31 out of range (0 .. 8) (BioPieces::BackTrackError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/biopieces-0.3.6/lib/biopieces/seq/backtrack.rb:74:in `patmatch'
        from /usr/local/lib/ruby/gems/2.0.0/gems/biopieces-0.3.6/lib/biopieces/commands/clip_primer.rb:166:in `block (3 levels) in clip_primer'
```

The culprit is line 142 in clip_primer.rb where dist can be longer than entry.length

```
   dist  = options[:search_distance] || entry.length
```

**Comment by maasha** [comment]
Fixed
